//
// Generated file, do not edit! Created by nedtool 5.4 from myID.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __MYID_M_H
#define __MYID_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>myID.msg:17</tt> by nedtool.
 * <pre>
 * message MyID
 * {
 *     int source;
 *     int destination;
 *     int degre;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class MyID : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int degre;
    int hopCount;

  private:
    void copy(const MyID& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyID&);

  public:
    MyID(const char *name=nullptr, short kind=0);
    MyID(const MyID& other);
    virtual ~MyID();
    MyID& operator=(const MyID& other);
    virtual MyID *dup() const override {return new MyID(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getDegre() const;
    virtual void setDegre(int degre);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MyID& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MyID& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MYID_M_H

